name: terraform ki practise

on: 
  push: 
    branches: 
      - main
      - feature-1
  pull_request: 
    branches: 
      - main
      - feature-1


jobs:
  my_first_job:
    name: my_first_job
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: touch sumit.txt
      - name: data entry
        run: |
          echo "mera name jony h" > sumit.txt
          cat sumit.txt

      
      
