name: terraform ki practise

on: 
  push: 
    branches: 
      - main
      - feature-2
  pull_request: 
    branches: 
      - main
      - feature-2


jobs:
  my_first_job:
    name: terraform init & plan
    runs-on: ubuntu-latest
    steps:
      - name: terraform setup
        uses: hashicorp/setup-terraform@v4
      - name: checkout repo
        uses: actions/checkout@v7.0.0
      - name: tera init
        run: terraform init
      - name: tera fmt
        run: terraform fmt
      - name: tera plan
        run: terraform plan
      
      
